# Generated by Django 4.2.4 on 2023-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsistemas', '0002_producto_tipoproducto_delete_pruebajd1_producto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagenproducto/%Y/%m/%d', verbose_name='Imagen Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciocompra',
            field=models.FloatField(default=0, verbose_name='Precio Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioventa',
            field=models.FloatField(default=0, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Tipo Producto'),
        ),
        migrations.DeleteModel(
            name='pruebajd1',
        ),
    ]
