# Generated by Django 4.2.4 on 2023-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdsistemas', '0003_alter_producto_descripcion_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=100, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
