# Generated by Django 4.2.4 on 2023-08-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdsistemas', '0004_producto_codigo_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jdsistemas.tipoproducto', verbose_name='Tipo producto'),
        ),
    ]
